# Brand.create(name: "シャネル")
# Brand.create(name: "グッチ")
# Brand.create(name: "ルイヴィトン")
# Brand.create(name: "シュプリーム")
# Brand.create(name: "アディダス")
# Brand.create(name: "ナイキ")
# Brand.create(name: "プーマ")
# Brand.create(name: "ブランド一覧")

# Term.create(name: '1~2日で発送')
# Term.create(name: '2~3日で発送')
# Term.create(name: '4~7日で発送')

# Size.create(name: 'XXS以下')
# Size.create(name: 'XS (SS)')
# Size.create(name: 'S')
# Size.create(name: 'M')
# Size.create(name: 'L')
# Size.create(name: 'XL (LL)')
# Size.create(name: '2XL (3L)')
# Size.create(name: '3XL (4L)')
# Size.create(name: '4XL (5L)')


# Condition.create(name: '新品、未使用')
# Condition.create(name: '未使用に近い')
# Condition.create(name: '目立った傷や汚れなし')
# Condition.create(name: 'やや傷や汚れなし')
# Condition.create(name: '傷や汚れあり')
# Condition.create(name: '全体的に状態が悪い')

Shipping.create(name: "未定")
Shipping.create(name: "らくらくメルカリ便")
Shipping.create(name: "ゆうメール")
Shipping.create(name: "レターパック")
Shipping.create(name: "普通郵便(定形、定形外)")
Shipping.create(name: "クロネコヤマト")
Shipping.create(name: "ゆうパック")
Shipping.create(name: "クリックポスト")
Shipping.create(name: "ゆうパケット")